# Generated by Django 3.0.2 on 2020-02-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='currencies',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('CHF', 'Swiss Franc'), ('GBP', 'Pound Sterling'), ('EUR', 'Euro'), ('MKD', 'Denar')], default='EUR', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='distances',
            field=models.CharField(choices=[('KM', 'KM'), ('Mile', 'Mile')], default='KM', max_length=20),
        ),
    ]
