export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const USER_UPDATE = "USER_UPDATE";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";

export const GET_COMPANY = "GET_COMPANY";
export const EDIT_COMPANY = "EDIT_COMPANY";
export const ADD_USER_TO_COMPANY = "ADD_USER_TO_COMPANY";
export const GET_COMPANY_USERS = "GET_COMPANY_USERS";

export const MESSAGE = "MESSAGE";

export const GET_VEHICLES = "GET_VEHICLES";
export const ADD_VEHICLE = "ADD_VEHICLE";
export const EDIT_VEHICLE = "EDIT_VEHICLE";
export const GET_VEHICLE_DETAIL = "GET_VEHICLE_DETAIL";
export const DELETE_VEHICLE = "DELETE_VEHICLE";

export const ADD_REPAIR = "ADD_REPAIR";

export const GET_ALL_REPAIR_SHOPS = "GET_ALL_REPAIR_SHOPS";
export const GET_REPAIR_SHOPS = "GET_REPAIR_SHOPS";
export const GET_REPAIR_SHOP_DETAIL = "GET_REPAIR_SHOP_DETAIL";
export const ADD_REPAIR_SHOP = "ADD_REPAIR_SHOP";
export const EDIT_REPAIR_SHOP = "EDIT_REPAIR_SHOP";
export const DELETE_REPAIR_SHOP = "DELETE_REPAIR_SHOP";

export const GET_DASHBOARD_INFO = "GET_DASHBOARD_INFO";
