# Generated by Django 3.0.2 on 2020-02-20 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repairs', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('manufactured', models.DateField(blank=True)),
                ('distance_passed', models.DecimalField(blank=True, decimal_places=2, max_digits=9)),
                ('functional', models.BooleanField()),
                ('details', models.CharField(blank=True, max_length=200)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
                ('repairs', models.ManyToManyField(to='repairs.Repair')),
            ],
        ),
    ]
