# Generated by Django 3.0.2 on 2020-02-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repairs', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='repairs',
            field=models.ManyToManyField(blank=True, to='repairs.Repair'),
        ),
    ]
