# Generated by Django 3.0.2 on 2020-02-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_auto_20200220_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='distance_passed',
            field=models.IntegerField(blank=True),
        ),
    ]
