# Generated by Django 3.0.2 on 2020-02-25 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repairs', '0007_auto_20200225_1012'),
        ('vehicles', '0004_auto_20200222_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='repairs',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='repairs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='repairs.Repair'),
        ),
    ]
