# Generated by Django 3.0.2 on 2020-03-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_vehicle_repairs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='distance_passed',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
