# Generated by Django 3.0.2 on 2020-03-01 09:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0008_auto_20200301_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='distance_passed',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
