# Generated by Django 3.0.2 on 2020-03-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0009_auto_20200301_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='registered_till',
            field=models.DateField(blank=True, null=True),
        ),
    ]
