# Generated by Django 3.0.2 on 2020-03-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0010_vehicle_registered_till'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='registered_till',
            field=models.DateField(),
        ),
    ]
